# Use a lightweight web server as the base image
FROM nginx:alpine

# Copy the index.html file to the NGINX document root
COPY index.html /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80
